# Generated by Django 4.1.5 on 2023-01-13 10:00

import core.model.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('delete_time', models.DateTimeField(help_text='删除时间', null=True)),
                ('name', core.model.base.NotNullCharField(help_text='商品名称', max_length=200)),
                ('price', models.IntegerField(help_text='价格的数值')),
                ('currency', core.model.base.NotNullCharField(help_text='货币符号', max_length=200)),
                ('total', models.IntegerField(help_text='库存总数', null=True)),
                ('description', models.TextField(help_text='描述')),
                ('thumbnail', core.model.base.NullCharField(blank=True, help_text='商品的缩略图地址', max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
